#!/usr/bin/env python3
"""CAS repository validator and index generator.

This tool validates Markdown engineering artifacts and rebuilds lightweight
repository indexes. It never makes engineering or certification decisions.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class ArtifactRule:
    prefix: str
    required_headings: tuple[str, ...]


RULES = {
    "TA": ArtifactRule("TA", ("Transition", "Intent", "Decision")),
    "ED": ArtifactRule("ED", ("Decision", "Rationale", "Disposition")),
    "FC": ArtifactRule("FC", ("Status", "Source", "Proposal")),
    "ECP": ArtifactRule("ECP", ("Current State", "Proposed Change", "Disposition")),
    "SA": ArtifactRule("SA", ("Scene Overview", "Engineering Intent", "Certification")),
    "SS": ArtifactRule("SS", ("Scene", "Score", "Recommendation")),
    "SC": ArtifactRule("SC", ("Certification ID", "Status", "Certification Statement")),
}

ARTIFACT_RE = re.compile(r"^(TA|ED|FC|ECP|SA|SS|SC)-(\d{4})_.+\.md$")
HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$", re.MULTILINE)


def markdown_files() -> Iterable[Path]:
    for path in ROOT.rglob("*.md"):
        if ".git" not in path.parts and "automation" not in path.parts:
            yield path


def validate() -> list[str]:
    errors: list[str] = []
    seen: dict[tuple[str, str], Path] = {}

    for path in markdown_files():
        match = ARTIFACT_RE.match(path.name)
        if not match:
            continue

        prefix, number = match.groups()
        key = (prefix, number)
        if key in seen:
            errors.append(
                f"Duplicate artifact ID {prefix}-{number}: "
                f"{seen[key].relative_to(ROOT)} and {path.relative_to(ROOT)}"
            )
        else:
            seen[key] = path

        text = path.read_text(encoding="utf-8")
        headings = {h.strip().casefold() for h in HEADING_RE.findall(text)}
        for required in RULES[prefix].required_headings:
            if required.casefold() not in headings:
                errors.append(
                    f"{path.relative_to(ROOT)} is missing heading: {required}"
                )

        if "draft" not in text.casefold() and "candidate" not in text.casefold() \
                and "accepted" not in text.casefold() and "certified" not in text.casefold() \
                and "rejected" not in text.casefold() and "deferred" not in text.casefold():
            errors.append(
                f"{path.relative_to(ROOT)} does not contain a recognizable lifecycle status"
            )

    return errors


def artifact_rows(prefix: str) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for path in markdown_files():
        match = ARTIFACT_RE.match(path.name)
        if not match or match.group(1) != prefix:
            continue
        text = path.read_text(encoding="utf-8")
        title = next((line.lstrip("# ").strip() for line in text.splitlines() if line.startswith("#")), path.stem)
        status_match = re.search(r"(?im)^\s*(?:\*\*)?Status(?:\*\*)?\s*[:\n]\s*([^\n]+)", text)
        status = status_match.group(1).strip(" *") if status_match else "Unspecified"
        rows.append((f"{match.group(1)}-{match.group(2)}", title, status))
    return sorted(rows)


def write_index(prefix: str, destination: Path, heading: str) -> None:
    rows = artifact_rows(prefix)
    lines = [f"# {heading}", "", "<!-- Generated by automation/cas_automation.py. -->", "", "| ID | Title | Status |", "|---|---|---|"]
    if rows:
        lines.extend(f"| {artifact_id} | {title.replace('|', '/')} | {status.replace('|', '/')} |" for artifact_id, title, status in rows)
    else:
        lines.append("| — | No artifacts found | — |")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")


def rebuild_indexes() -> None:
    generated = ROOT / "generated"
    write_index("TA", generated / "TRANSITION_AUDIT_INDEX.md", "Transition Audit Index")
    write_index("ED", generated / "ENGINEERING_DECISION_INDEX.md", "Engineering Decision Index")
    write_index("FC", generated / "FRAMEWORK_CONTRIBUTION_INDEX.md", "Framework Contribution Index")
    write_index("ECP", generated / "ENGINEERING_CHANGE_PROPOSAL_INDEX.md", "Engineering Change Proposal Index")
    write_index("SA", generated / "SCENE_ANALYSIS_INDEX.md", "Scene Analysis Index")
    write_index("SC", generated / "SCENE_CERTIFICATION_INDEX.md", "Scene Certification Index")


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate and index CAS engineering artifacts.")
    parser.add_argument("command", choices=("validate", "index", "all"))
    args = parser.parse_args()

    if args.command in {"index", "all"}:
        rebuild_indexes()
        print("CAS indexes rebuilt.")

    if args.command in {"validate", "all"}:
        errors = validate()
        if errors:
            print("CAS validation failed:", file=sys.stderr)
            for error in errors:
                print(f"- {error}", file=sys.stderr)
            return 1
        print("CAS validation passed.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
